name: iOS Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build iOS app
      run: |
        xcodebuild -project "Frame Grabber.xcodeproj" -scheme "Frame Grabber Release" -sdk iphoneos -configuration Release -allowProvisioningUpdates
